
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/google/gopacket"
  version = "1.1.14"

[[constraint]]
  branch = "master"
  name = "github.com/google/safebrowsing"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  name = "github.com/klauspost/oui"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/krolaw/dhcp4"

[[constraint]]
  branch = "master"
  name = "github.com/ktscholl/go-nmap"

[[constraint]]
  name = "github.com/lestrrat/go-apache-logformat"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/miekg/dns"

[[constraint]]
  branch = "master"
  name = "github.com/pebbe/zmq4"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/satori/uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/tensorflow/tensorflow"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/tomazk/envcfg"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "gonum.org/v1/plot"
