
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


# Override is more powerful than constraint; since some of our dependent
# libraries have started using dep, they've not all agreed on the right way to
# depend on protobufs.  This settles it.
[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/google/gopacket"
  version = "1.1.14"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  name = "github.com/klauspost/oui"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/krolaw/dhcp4"

[[constraint]]
  branch = "master"
  name = "github.com/lair-framework/go-nmap"

[[constraint]]
  name = "github.com/lestrrat/go-apache-logformat"
  version = "2.0.0"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.8"

[[constraint]]
  branch = "master"
  name = "github.com/pebbe/zmq4"

# Use ~ for pre-1.0-- see also notes on github page about future 0.9.x, 1.x, etc.
[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "~0.8.0"

[[constraint]]
  name = "github.com/satori/uuid"
  version = "1.2.0"

# This constraint is much stricter than others which appear here
# because we deliver a matched libtensorflow.so
[[constraint]]
  name = "github.com/tensorflow/tensorflow"
  version = "=1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/tomazk/envcfg"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "~0.3.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "gonum.org/v1/plot"

[[constraint]]
  branch = "master"
  name = "github.com/pquerna/otp"

[[constraint]]
  branch = "master"
  name = "github.com/ttacon/libphonenumber"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/NYTimes/gziphandler"
  version = "1.0.1"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "1.2.0"

# pre-1.0, use ~; make sure to audit changelog
[[constraint]]
  name = "cloud.google.com/go"
  version = "~0.24.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

# pre-1.0, use ~; make sure to audit changelog
[[constraint]]
  name = "golang.org/x/text"
  version = "~0.3.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  name = "github.com/markbates/goth"
  version = "1.46.0"

[[constraint]]
  name = "github.com/guregu/null"
  version = "3.4.0"
