
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# For whatever reason, dep can't see that cloud.google.com/go needs this.
# So the [required] statement forces it to be included.
required = ["google.golang.org/api"]

# Override is more powerful than constraint; since some of our dependent
# libraries have started using dep, they've not all agreed on the right way to
# depend on protobufs.  This settles it.
[[override]]
  name = "github.com/golang/protobuf"
  version = "1.3.2"

[[constraint]]
  name = "github.com/google/gopacket"
  version = "1.1.17"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/klauspost/oui"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/krolaw/dhcp4"

[[constraint]]
  branch = "master"
  name = "github.com/lair-framework/go-nmap"

[[constraint]]
  name = "github.com/lestrrat-go/apache-logformat"
  version = "2.0.4"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.1.20"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "^1.1.0"

# If this is newer then prometheus/client_golang barfs
[[override]]
  name = "github.com/prometheus/procfs"
  version = "~0.0.4"

[[constraint]]
  name = "github.com/satori/uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sethvargo/go-diceware"
  version = "~0.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/tomazk/envcfg"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.27.1"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.2.0"

[[constraint]]
  name = "github.com/ttacon/libphonenumber"
  version = "1.0.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/NYTimes/gziphandler"
  version = "1.1.1"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "1.2.0"

# pre-1.0, use ~; make sure to audit changelog
[[constraint]]
  name = "cloud.google.com/go"
  version = "~0.52.0"

# Override is more powerful than constraint; github.com/dhduvall/gcloudzap
# sets cloud.google.com/go ~ 0.32.0, and we want to go newer.
[[override]]
  name = "cloud.google.com/go"
  version = "~0.52.0"

[[constraint]]
  name = "google.golang.org/api"
  version = "~0.17.0"

# Override is more powerful than constraint; github.com/go-acme/lego depends on
# google.golang.org/api@master, which dep considers to be outside of the
# version stream.  We want to specifically choose 0.17.0.
[[override]]
  name = "google.golang.org/api"
  version = "~0.17.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.10.0"

# pre-1.0, use ~; make sure to audit changelog
[[constraint]]
  name = "golang.org/x/text"
  version = "~0.3.2"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.10"

[[constraint]]
  name = "github.com/markbates/goth"
  version = "1.56.0"

[[constraint]]
  name = "github.com/guregu/null"
  version = "3.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/tatsushid/go-prettytable"

[[constraint]]
  branch = "master"
  name = "github.com/dhduvall/gcloudzap"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-acme/lego"
  version = "2.7.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/m-lab/ndt7-client-go"

[[constraint]]
  name = "github.com/gliderlabs/ssh"
  version = "~0.2.2"

[[constraint]]
  name = "nanomsg.org/go/mangos/v2"
  version = "2.0.2"

[[constraint]]
  name = "github.com/unrolled/secure"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/dhduvall/closestmatch"

[[constraint]]
  name = "github.com/fsouza/fake-gcs-server"
  version = "1.17.0"

