/*
 * COPYRIGHT 2018 Brightgate Inc.  All rights reserved.
 *
 * This copyright notice is Copyright Management Information under 17 USC 1202
 * and is included to protect this work and deter copyright infringement.
 * Removal or alteration of this Copyright Management Information without the
 * express written permission of Brightgate Inc is prohibited, and any
 * such unauthorized removal or alteration will be a violation of federal law.
 */
// vim :set ts=2 sw=2 sts=2 et :
export default [
  {
    category: 'recent', // XXX this is problematic
    manufacturer: 'Apple',
    model: 'iPhone 8',
    kind: 'ios',
    confidence: 0.99,
    network_name: 'nosy-neighbor',
    os_version: 'iOS 11.0.1',
    owner: 'unknown',
    activated: '',
    owner_phone: '',
    owner_email: '',
    media: 'mobile-phone-1',
    uniqid: 'c8:bc:c8:3a:8a:24',
    hwaddr: 'c8:bc:c8:3a:8a:24',
    ring: 'standard',
    active: false,
  },
  {
    manufacturer: 'Apple',
    model: 'iPhone 6 Plus',
    kind: 'ios',
    confidence: 0.99,
    network_name: 'CAT',
    os_version: 'iOS 10.3.3',
    owner: 'Christopher Thorpe',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-259-4751',
    owner_email: 'cat@brightgate.com',
    media: 'mobile-phone-1',
    uniqid: 'c8:bc:c8:83:1c:45',
    hwaddr: 'c8:bc:c8:83:1c:45',
    ring: 'standard',
    active: true,
    last_scan: '2018-03-27T20:53:45+00:00',
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S8',
    kind: 'android',
    confidence: 0.99,
    network_name: 'sch',
    os_version: 'Android',
    owner: 'Stephen Hahn',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-259-4751',
    owner_email: 'stephen@brightgate.com',
    media: 'mobile-phone-1',
    uniqid: 'bc:47:60:8d:d5:5b',
    hwaddr: 'bc:47:60:8d:d5:5b',
    ring: 'standard',
    active: true,
  },
  {
    manufacturer: 'Apple',
    model: 'iPad 2',
    kind: 'ios',
    confidence: 0.99,
    network_name: 'catpad',
    os_version: 'iOS 9.1.1',
    owner: 'Christopher Thorpe',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-259-4751',
    owner_email: 'cat@brightgate.com',
    notification: 'notification',
    media: 'tablet',
    uniqid: 'c8:bc:c8:83:1c:33',
    hwaddr: 'c8:bc:c8:83:1c:33',
    ring: 'standard',
    active: false,
  },
  {
    manufacturer: 'Apple Inc.',
    model: 'Macbook Pro',
    kind: 'computer',
    confidence: 0.99,
    network_name: 'catbook',
    os_version: 'MacOS 10.12.4',
    owner: 'Christopher Thorpe',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-259-4751',
    owner_email: 'cat@brightgate.com',
    media: 'laptop-2',
    uniqid: 'c8:bc:c8:83:1c:11',
    hwaddr: 'c8:bc:c8:83:1c:11',
    ring: 'standard',
    active: false,
  },
  {
    manufacturer: 'Toshiba',
    model: 'CB35-A3120 Chromebook',
    kind: 'computer',
    confidence: 0.99,
    network_name: 'schbook',
    os_version: 'Linux',
    owner: 'Stephen Hahn',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-259-4751',
    owner_email: 'stephen@brightgate.com',
    media: 'laptop-1',
    uniqid: 'c8:aa:c8:83:1c:11',
    hwaddr: 'c8:aa:c8:83:1c:11',
    ring: 'standard',
    active: false,
  },
  {
    manufacturer: 'Toshiba',
    model: 'Satellite L755',
    kind: 'computer',
    confidence: 0.99,
    network_name: 'jsmith',
    os_version: 'Windows 10',
    owner: 'Jack Smith',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-867-5309',
    owner_email: 'jack@brightgate.com',
    alert: 'alert',
    media: 'laptop-1',
    uniqid: 'aa:aa:c8:83:1c:11',
    hwaddr: 'aa:aa:c8:83:1c:11',
    ring: 'quarantine',
    last_scan: '2018-04-11T20:53:02+00:00',
    active: false,
  },
  {
    manufacturer: 'Sonos',
    model: 'CONNECT:AMP',
    kind: 'media',
    confidence: 0.99,
    network_name: 'SONOS',
    os_version: 'SONOS',
    owner: 'Christopher Thorpe',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-259-4751',
    owner_email: 'cat@brightgate.com',
    media: 'radio-3',
    uniqid: '94:9F:3E:8A:87:27',
    hwaddr: '94:9F:3E:8A:87:27',
    ring: 'standard',
    active: false,
  },
  {
    manufacturer: 'Apple',
    model: 'Apple TV',
    kind: 'media',
    confidence: 0.99,
    network_name: 'cat-apple-TV',
    os_version: 'Apple TV',
    owner: 'Stephen Hahn',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-259-4751',
    owner_email: 'stephen@brightgate.com',
    media: 'television',
    uniqid: 'c8:bc:c8:83:1c:11',
    hwaddr: 'c8:bc:c8:83:1c:11',
    ring: 'standard',
    active: false,
  },
  {
    manufacturer: 'Samsung',
    model: 'UN50MU6300 Series 6',
    kind: 'media',
    confidence: 0.75,
    network_name: 'samsung-un50',
    os_version: '3.0.1',
    owner: 'Christopher Thorpe',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-259-4751',
    owner_email: 'cat@brightgate.com',
    notification: 'notification',
    media: 'television',
    uniqid: 'c8:bc:c8:83:1c:22',
    hwaddr: 'c8:bc:c8:83:1c:22',
    ring: 'standard',
    active: false,
  },
  {
    manufacturer: 'Logitech',
    model: 'Logic Circle Security Camera 1',
    kind: 'iot',
    confidence: 0.48,
    network_name: 'logicircle-1',
    os_version: '4.4.4.448',
    owner: 'Christopher Thorpe',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-259-4751',
    owner_email: 'cat@brightgate.com',
    media: 'webcam-1',
    uniqid: 'c8:bc:c8:89:1c:22',
    hwaddr: 'c8:bc:c8:89:1c:22',
    ring: 'standard',
    active: false,
  },
  {
    manufacturer: 'Logitech',
    model: 'Logic Circle Security Camera 2',
    kind: 'iot',
    confidence: 0.99,
    network_name: 'logicircle-2',
    os_version: '4.4.4.448',
    owner: 'Christopher Thorpe',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-259-4751',
    owner_email: 'cat@brightgate.com',
    media: 'webcam-1',
    uniqid: 'c1:bc:c1:19:1c:22',
    hwaddr: 'c1:bc:c1:19:1c:22',
    ring: 'standard',
    active: false,
  },
  {
    manufacturer: 'Unknown',
    model: 'Unknown',
    kind: 'unknown',
    confidence: 0.99,
    network_name: 'device',
    os_version: 'unknown',
    owner: 'Christopher Thorpe',
    activated: 'August 10, 2017',
    owner_phone: '+1-617-259-4751',
    owner_email: 'cat@brightgate.com',
    media: 'interface-question-mark',
    uniqid: 'c1:ac:c1:19:1c:22',
    hwaddr: 'c1:ac:c1:19:1c:22',
    ring: 'standard',
    active: false,
  },
];
