/*
 * COPYRIGHT 2019 Brightgate Inc.  All rights reserved.
 *
 * This copyright notice is Copyright Management Information under 17 USC 1202
 * and is included to protect this work and deter copyright infringement.
 * Removal or alteration of this Copyright Management Information without the
 * express written permission of Brightgate Inc is prohibited, and any
 * such unauthorized removal or alteration will be a violation of federal law.
 *
 */

// We want the const values to be CAP_UNDERSCORE to make it easier to compare
// with kernel and hostapd constants.  go-lint doesn't like that, but it doesn't
// provide a #pragma-like way to indicate that "I understand you don't like the
// following code snippet, but it's really what I want".  Instead, we have to
// indicate that the entire file should be ignored:
//
// Code generated by hand. DO NOT EDIT.

package wificaps

// The following are all of the HT (802.11n) capabilities we detect
const (
	HTCAP_LDPC = iota
	HTCAP_HT20
	HTCAP_HT20_40
	HTCAP_HT20_SGI
	HTCAP_HT40_SGI
	HTCAP_TX_STBC
	HTCAP_RX_STBC1
	HTCAP_RX_STBC12
	HTCAP_RX_STBC123
	HTCAP_DELAYED_BA
	HTCAP_MAX_AMSDU_3839
	HTCAP_MAX_AMSDU_7935
	HTCAP_DSSS_CCK
)

var htCaps = map[int]capability{
	HTCAP_LDPC:           {0x1, 0x1, "LDPC"},
	HTCAP_HT20:           {0x2, 0x0, "HT20"},
	HTCAP_HT20_40:        {0x2, 0x2, "HT20/HT40"},
	HTCAP_HT20_SGI:       {0x20, 0x20, "RX HT20 SGI"},
	HTCAP_HT40_SGI:       {0x40, 0x40, "RX HT40 SGI"},
	HTCAP_TX_STBC:        {0x80, 0x80, "TX STBC"},
	HTCAP_RX_STBC1:       {0x300, 0x100, "RX-STBC1"},
	HTCAP_RX_STBC12:      {0x300, 0x200, "RX-STBC12"},
	HTCAP_RX_STBC123:     {0x300, 0x300, "RX-STBC123"},
	HTCAP_DELAYED_BA:     {0x400, 0x400, "HT Delayed Block Ack"},
	HTCAP_MAX_AMSDU_3839: {0x800, 0x0, "MAX AMSDU 3839"},
	HTCAP_MAX_AMSDU_7935: {0x800, 0x800, "MAX AMSDU 7935"},
	HTCAP_DSSS_CCK:       {0x1000, 0x1000, "DSSS/CCK HT40"},
}

// The following are all of the VHT (802.11ac) capabilities we detect
const (
	VHTCAP_MAX_MPDU_7991 = iota
	VHTCAP_MAX_MPDU_11454
	VHTCAP_CHANNEL_160
	VHTCAP_CHANNEL_160_8080
	VHTCAP_RX_LDPC
	VHTCAP_VHT80_SGI
	VHTCAP_VHT160_SGI
	VHTCAP_TX_STBC
	VHTCAP_RX_STBC1
	VHTCAP_RX_STBC2
	VHTCAP_RX_STBC3
	VHTCAP_RX_STBC4
	VHTCAP_SU_BEAMFORMER
	VHTCAP_SU_BEAMFORMEE
	VHTCAP_MU_BEAMFORMER
	VHTCAP_MU_BEAMFORMEE
	VHTCAP_RX_ANTENNA_PATTERN
	VHTCAP_TX_ANTENNA_PATTERN
	VHTCAP_BF_ANTENNA_2
	VHTCAP_BF_ANTENNA_3
	VHTCAP_BF_ANTENNA_4
	VHTCAP_SOUNDING_DIMENSION_1
	VHTCAP_SOUNDING_DIMENSION_2
	VHTCAP_SOUNDING_DIMENSION_3
	VHTCAP_SOUNDING_DIMENSION_4
	VHTCAP_MAX_A_MPDU_LEN_EXP1
	VHTCAP_MAX_A_MPDU_LEN_EXP2
	VHTCAP_MAX_A_MPDU_LEN_EXP3
	VHTCAP_MAX_A_MPDU_LEN_EXP4
	VHTCAP_MAX_A_MPDU_LEN_EXP5
	VHTCAP_MAX_A_MPDU_LEN_EXP6
	VHTCAP_MAX_A_MPDU_LEN_EXP7
)

var vhtCaps = map[int]capability{
	VHTCAP_MAX_MPDU_7991:        {0x3, 0x1, "MPDU_7991"},
	VHTCAP_MAX_MPDU_11454:       {0x3, 0x2, "MPDU_11454"},
	VHTCAP_CHANNEL_160:          {0xf, 0x4, "160MHz"},
	VHTCAP_CHANNEL_160_8080:     {0xf, 0x8, "160MHz, 80+80MHz"},
	VHTCAP_RX_LDPC:              {0x10, 0x10, "RX LDPC"},
	VHTCAP_VHT80_SGI:            {0x20, 0x20, "short GI (80 MHz)"},
	VHTCAP_VHT160_SGI:           {0x40, 0x40, "short GI (160/80+80 MHz)"},
	VHTCAP_TX_STBC:              {0x80, 0x80, "TX STBC"},
	VHTCAP_RX_STBC1:             {0x700, 0x100, "RX STBC1"},
	VHTCAP_RX_STBC2:             {0x700, 0x200, "RX STBC2"},
	VHTCAP_RX_STBC3:             {0x700, 0x300, "RX STBC3"},
	VHTCAP_RX_STBC4:             {0x700, 0x400, "RX STBC4"},
	VHTCAP_SU_BEAMFORMER:        {0x800, 0x800, "SU Beamformer"},
	VHTCAP_SU_BEAMFORMEE:        {0x1000, 0x1000, "SU Beamformee"},
	VHTCAP_MU_BEAMFORMER:        {0x80000, 0x80000, "MU Beamformer"},
	VHTCAP_MU_BEAMFORMEE:        {0x100000, 0x100000, "MU Beamformee"},
	VHTCAP_RX_ANTENNA_PATTERN:   {0x10000000, 0x10000000, "RX antenna pattern"},
	VHTCAP_TX_ANTENNA_PATTERN:   {0x20000000, 0x20000000, "TX antenna pattern"},
	VHTCAP_BF_ANTENNA_2:         {0xe000, 0x2000, "BF_ANTENNA2"},
	VHTCAP_BF_ANTENNA_3:         {0xe000, 0x4000, "BF_ANTENNA3"},
	VHTCAP_BF_ANTENNA_4:         {0xe000, 0x6000, "BF_ANTENNA4"},
	VHTCAP_SOUNDING_DIMENSION_1: {0x70000, 0x0, "SOUNDING_DIMENSION1"},
	VHTCAP_SOUNDING_DIMENSION_2: {0x70000, 0x10000, "SOUNDING_DIMENSION2"},
	VHTCAP_SOUNDING_DIMENSION_3: {0x70000, 0x20000, "SOUNDING_DIMENSION3"},
	VHTCAP_SOUNDING_DIMENSION_4: {0x70000, 0x30000, "SOUNDING_DIMENSION4"},
	VHTCAP_MAX_A_MPDU_LEN_EXP1:  {0x38000000, 0x8000000, "MAX_A_MPDU_LEN_EXP1"},
	VHTCAP_MAX_A_MPDU_LEN_EXP2:  {0x38000000, 0x10000000, "MAX_A_MPDU_LEN_EXP2"},
	VHTCAP_MAX_A_MPDU_LEN_EXP3:  {0x38000000, 0x18000000, "MAX_A_MPDU_LEN_EXP3"},
	VHTCAP_MAX_A_MPDU_LEN_EXP4:  {0x38000000, 0x20000000, "MAX_A_MPDU_LEN_EXP4"},
	VHTCAP_MAX_A_MPDU_LEN_EXP5:  {0x38000000, 0x28000000, "MAX_A_MPDU_LEN_EXP5"},
	VHTCAP_MAX_A_MPDU_LEN_EXP6:  {0x38000000, 0x30000000, "MAX_A_MPDU_LEN_EXP6"},
	VHTCAP_MAX_A_MPDU_LEN_EXP7:  {0x38000000, 0x38000000, "MAX_A_MPDU_LEN_EXP7"},
}
